/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface DigitalReserveWithdrawalContract
  extends Truffle.Contract<DigitalReserveWithdrawalInstance> {
  "new"(
    _drcAddress: string,
    meta?: Truffle.TransactionDetails
  ): Promise<DigitalReserveWithdrawalInstance>;
}

type AllEvents = never;

export interface DigitalReserveWithdrawalInstance
  extends Truffle.ContractInstance {
  withdraw: {
    (
      _digitalReserve: string,
      percentage: number | BN | string,
      minAmountOut: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _digitalReserve: string,
      percentage: number | BN | string,
      minAmountOut: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _digitalReserve: string,
      percentage: number | BN | string,
      minAmountOut: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _digitalReserve: string,
      percentage: number | BN | string,
      minAmountOut: number | BN | string,
      deadline: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    withdraw: {
      (
        _digitalReserve: string,
        percentage: number | BN | string,
        minAmountOut: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _digitalReserve: string,
        percentage: number | BN | string,
        minAmountOut: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _digitalReserve: string,
        percentage: number | BN | string,
        minAmountOut: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _digitalReserve: string,
        percentage: number | BN | string,
        minAmountOut: number | BN | string,
        deadline: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
